# Generated by Django 3.2.9 on 2021-11-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicArchiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unittitle', models.CharField(max_length=100)),
                ('unitstart_date', models.IntegerField()),
                ('unitend_date', models.IntegerField()),
                ('scopecontent', models.TextField(blank=True, null=True)),
                ('arrangement', models.TextField(blank=True, null=True)),
                ('custodhist', models.TextField(blank=True, null=True)),
                ('relatedmaterial', models.TextField(blank=True, null=True)),
                ('bioghist', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoteAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhysDescType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.CreateModel(
            name='UnitIdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.basicarchivemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.unitidtype')),
            ],
        ),
        migrations.CreateModel(
            name='PhysDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_physdesc', to='catalogue.basicarchivemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.physdesctype')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('firstNames', models.CharField(blank=True, max_length=60, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, null=True, related_name='person', to='catalogue.BasicArchiveModel')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.noteaudience')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_note', to='catalogue.basicarchivemodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.notetype')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.basicarchivemodel')),
            ],
        ),
        migrations.CreateModel(
            name='cat_to_gaz_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.basicarchivemodel')),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.locus')),
            ],
        ),
        migrations.CreateModel(
            name='BibliographicReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('item', models.ManyToManyField(blank=True, null=True, related_name='biblio_ref', to='catalogue.BasicArchiveModel')),
            ],
        ),
        migrations.AddField(
            model_name='basicarchivemodel',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='catalogue.Language'),
        ),
        migrations.AddField(
            model_name='basicarchivemodel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.level'),
        ),
        migrations.AddField(
            model_name='basicarchivemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.basicarchivemodel'),
        ),
        migrations.AddField(
            model_name='basicarchivemodel',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.repository'),
        ),
    ]
