# Generated by Django 3.2.9 on 2021-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicarchivemodel',
            name='language',
            field=models.ManyToManyField(blank=True, to='catalogue.Language'),
        ),
        migrations.AlterField(
            model_name='bibliographicreference',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='biblio_ref', to='catalogue.BasicArchiveModel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='person', to='catalogue.BasicArchiveModel'),
        ),
    ]
