# Generated by Django 3.2.21 on 2023-09-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_many_to_many'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(blank=True, max_length=60, null=True)),
                ('Forename', models.CharField(blank=True, max_length=60, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.person')),
            ],
        ),
    ]
