# Generated by Django 3.2.21 on 2023-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alternativename'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DateFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='DateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
