# Generated by Django 3.2.21 on 2023-09-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_referencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='referenceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.referencetype'),
        ),
    ]
