# Generated by Django 3.2.21 on 2023-09-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_Variant_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativename',
            old_name='Forename',
            new_name='forename',
        ),
        migrations.RenameField(
            model_name='alternativename',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='alternativename',
            name='DateTo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
