# Generated by Django 3.2.21 on 2023-09-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alternativename_renames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='referenceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.referencetype'),
        ),
    ]
