# Generated by Django 3.2.21 on 2023-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_person_referencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativename',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
