# Generated by Django 3.2.21 on 2023-09-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20230921_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativename',
            name='referenceType',
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.TextField(blank=True, null=True)),
                ('referenceType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.referencetype')),
            ],
        ),
    ]
