# Generated by Django 3.2.21 on 2023-09-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_reference_refactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='uri',
            new_name='reference',
        ),
    ]
