# Generated by Django 3.2.21 on 2023-09-25 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_rename_uri_reference_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='referenceType',
        ),
    ]
