# Generated by Django 3.2.21 on 2023-09-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_remove_person_referencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.person'),
        ),
    ]
