# Generated by Django 3.2.21 on 2023-09-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_reference_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativename',
            name='DateFrom',
        ),
        migrations.RemoveField(
            model_name='alternativename',
            name='DateTo',
        ),
        migrations.RemoveField(
            model_name='alternativename',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='alternativename',
            name='uri',
        ),
        migrations.AddField(
            model_name='alternativename',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
