# Generated by Django 3.2.21 on 2023-09-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alternate_name_nouris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='DateFrom',
        ),
        migrations.RemoveField(
            model_name='person',
            name='DateTo',
        ),
    ]
