#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python /app/manage.py collectstatic --noinput

#compress_enabled() {
#python << END
#import sys
#
#from environ import Env
#
#env = Env(DJANGO_COMPRESS_ENABLED=(bool, True))
#if env('DJANGO_COMPRESS_ENABLED'):
#    sys.exit(0)
#else:
#    sys.exit(1)
#
#END
#}
#
#if compress_enabled; then
#  # NOTE this command will fail if django-compressor is disabled
#  python /app/manage.py compress --force
#fi

python /app/manage.py compress --force
python manage.py runserver 0.0.0.0:8000
