# Generated by Django 3.2.9 on 2021-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='locus',
            field=models.ManyToManyField(blank=True, through='geo.Inscription_Locus', to='geo.Locus'),
        ),
        migrations.AlterField(
            model_name='locus',
            name='featuretype_fk',
            field=models.ManyToManyField(blank=True, to='geo.FeatureTypes'),
        ),
    ]
